version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - fastapi
    restart: always

  fastapi:
    image: ghcr.io/zhtv/my-fastapi-app:1
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - API_KEY=${API_KEY}
    deploy:
      replicas: 3
    ports:
      - "8000"
    restart: always